import './globals.css';
import type { Metadata } from 'next';
import { NextAuthProvider } from './providers';
import {
  LoginButton,
  LogoutButton,
  ProfileClientButton,
  ProfileServerButton,
} from '@/components/buttons';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <div className="flex justify-center items-center min-h-screen">
            <div>
              {session ? <LogoutButton /> : <LogoutButton />}
              {/* <RegisterButton /> */}
              <ProfileClientButton />
              <ProfileServerButton />

              {children}
            </div>
          </div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
